# Generated by Django 4.0.3 on 2022-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_test_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='folder',
            field=models.FileField(upload_to=''),
        ),
    ]
