# Generated by Django 4.0.3 on 2022-03-25 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_drive_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='File',
            new_name='file',
        ),
        migrations.AddField(
            model_name='drive',
            name='extension',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='drive',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='drive',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drive',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
