# Generated by Django 4.0.3 on 2022-03-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_drive_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='extension',
        ),
    ]
