# Generated by Django 4.0.3 on 2022-03-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_drive_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='extension',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='drive',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
