# Generated by Django 4.0.3 on 2022-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_drive_extension_alter_drive_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='extension',
            field=models.CharField(editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='drive',
            name='size',
            field=models.IntegerField(editable=False),
        ),
    ]
